# The Site Configurations

# Import the theme
theme: jekyll-theme-chirpy

# Web language and timezone
lang: es
timezone: Europe/Madrid

# jekyll-seo-tag settings
title: Asier Lara Arroyo
tagline: Hackeando el conocimiento
description: "Artículos, tutoriales y reflexiones sobre ciberseguridad y hacking ético."
url: "https://p3ix.github.io"
baseurl: ""

# GitHub info
github:
  username: p3ix

# Redes sociales
twitter:
  username: pirul4s

social:
  name: Asier Lara Arroyo
  email: asierlara03@gmail.com
  links:
    - https://twitter.com/pirul4s
    - https://github.com/p3ix
    #- https://www.linkedin.com/in/tuusuario  # cámbialo si tienes LinkedIn

webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

analytics:
  google:
    id:  # si usas Google Analytics
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

pageviews:
  provider:

# Tema oscuro por defecto
theme_mode: dark

# Recursos estáticos (CDN si se usa)
cdn:

# Avatar y Favicon (debes subir los archivos a /assets/img/)
avatar: /assets/img/avatar.png
favicon: /assets/img/favicon.ico

# Imagen por defecto para previsualización en redes sociales
social_preview_image: /assets/img/preview.png

# TOC en posts (tabla de contenidos)
toc: true

# Comentarios (opcional)
comments:
  provider:
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    strict:
    input_position:
    lang:
    reactions_enabled:

# Self-hosted assets
assets:
  self_host:
    enabled:
    env:

# Progressive Web App
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

# Paginación
paginate: 10
paginate_path: /page:num/

# Markdown engine y resaltado de código
markdown: kramdown
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Colecciones y estructuras internas
collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
